/**
 * CLAUDE.md Generator — synthesizes session history into an optimized context file.
 *
 * Analyzes:
 * - What tools the user uses most (indicates workflow patterns)
 * - What projects they work on (stack detection)
 * - Repeated phrases/context in user messages (should be in CLAUDE.md)
 * - Correction patterns (things Claude keeps getting wrong)
 * - Working directory patterns (project structure)
 */

import { readFile } from 'fs/promises';
import { join } from 'path';
import { homedir } from 'os';

/**
 * Analyze sessions and generate CLAUDE.md content suggestions.
 */
export function generateClaudeMdSuggestions(data) {
  const { projectsData, stats, features } = data;
  const allSessions = projectsData.flatMap(p => p.sessions);

  const sections = [];

  // 1. Stack detection from tool usage and project paths
  sections.push(detectStack(projectsData, stats));

  // 2. Working style from session patterns
  sections.push(detectWorkingStyle(allSessions, stats));

  // 3. Key projects
  sections.push(detectProjects(projectsData));

  // 4. Repeated context that should be encoded
  sections.push(extractRepeatedContext(allSessions));

  // 5. Tool preferences
  sections.push(detectToolPreferences(stats));

  return sections.filter(s => s !== null);
}

/**
 * Generate a complete CLAUDE.md file from suggestions.
 */
export function generateClaudeMd(data, projectName = null) {
  const suggestions = generateClaudeMdSuggestions(data);
  const lines = [];

  if (projectName) {
    lines.push(`# ${projectName}`);
  } else {
    lines.push('# Project Context');
  }
  lines.push('');
  lines.push('<!-- Generated by NarrowScore — narrowscore.com -->');
  lines.push('');

  for (const section of suggestions) {
    if (!section) continue;
    lines.push(`## ${section.title}`);
    if (section.description) lines.push(section.description);
    lines.push('');
    for (const item of section.items) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function detectStack(projectsData, stats) {
  const indicators = {
    node: false,
    python: false,
    react: false,
    playwright: false,
    sqlite: false,
    typescript: false,
  };

  // Infer from cwds and tool patterns
  const allCwds = projectsData.flatMap(p =>
    p.sessions.map(s => s.cwd).filter(Boolean)
  );

  // Infer from user messages
  const allText = projectsData.flatMap(p =>
    p.sessions.flatMap(s =>
      s.userMessages.map(m => m.text.toLowerCase())
    )
  ).join(' ');

  if (allText.includes('node') || allText.includes('npm') || allText.includes('esm')) indicators.node = true;
  if (allText.includes('python') || allText.includes('pip')) indicators.python = true;
  if (allText.includes('react') || allText.includes('jsx') || allText.includes('tsx')) indicators.react = true;
  if (allText.includes('playwright')) indicators.playwright = true;
  if (allText.includes('sqlite')) indicators.sqlite = true;
  if (allText.includes('typescript') || allText.includes('.ts')) indicators.typescript = true;

  const stack = Object.entries(indicators)
    .filter(([, v]) => v)
    .map(([k]) => k);

  if (stack.length === 0) return null;

  return {
    title: 'Stack',
    description: null,
    items: stack.map(s => {
      const labels = {
        node: 'Node.js (ESM)',
        python: 'Python',
        react: 'React',
        playwright: 'Playwright (browser automation)',
        sqlite: 'SQLite',
        typescript: 'TypeScript',
      };
      return labels[s] || s;
    }),
  };
}

function detectWorkingStyle(sessions, stats) {
  const items = [];

  // Session length patterns
  if (stats.avgTurnsPerSession > 15) {
    items.push('Prefers long, deep sessions (avg ' + stats.avgTurnsPerSession + ' turns)');
  } else if (stats.avgTurnsPerSession > 5) {
    items.push('Mixed session lengths (avg ' + stats.avgTurnsPerSession + ' turns)');
  } else {
    items.push('Quick, focused sessions (avg ' + stats.avgTurnsPerSession + ' turns)');
  }

  // Agent usage
  if (stats.totalAgentSpawns > 10) {
    items.push('Heavy subagent user — parallelizes research and tasks');
  } else if (stats.totalAgentSpawns > 0) {
    items.push('Occasional subagent usage');
  }

  // Time patterns
  if (sessions.length > 0) {
    const hours = sessions
      .map(s => s.timestamp ? new Date(s.timestamp).getHours() : null)
      .filter(h => h !== null);

    if (hours.length > 3) {
      const avg = Math.round(hours.reduce((a, b) => a + b, 0) / hours.length);
      if (avg < 10) items.push('Tends to work in the morning');
      else if (avg < 16) items.push('Tends to work during the day');
      else items.push('Tends to work in the evening/night');
    }
  }

  if (items.length === 0) return null;

  return {
    title: 'Working Style',
    description: null,
    items,
  };
}

function detectProjects(projectsData) {
  const items = [];

  for (const project of projectsData) {
    if (project.sessions.length >= 2) {
      const latest = project.sessions
        .filter(s => s.timestamp)
        .sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp))[0];

      const dateStr = latest ? new Date(latest.timestamp).toISOString().split('T')[0] : 'unknown';
      items.push(`\`${project.projectPath}\` — ${project.sessions.length} sessions (last: ${dateStr})`);
    }
  }

  if (items.length === 0) return null;

  return {
    title: 'Key Projects',
    description: null,
    items: items.slice(0, 10),
  };
}

function extractRepeatedContext(sessions) {
  const allUserMessages = sessions.flatMap(s =>
    s.userMessages.map(m => m.text)
  );

  if (allUserMessages.length < 5) return null;

  // Find common themes/keywords (simple frequency analysis)
  const wordFreq = {};
  const stopWords = new Set([
    'the', 'and', 'for', 'that', 'this', 'with', 'you', 'are', 'was',
    'have', 'has', 'had', 'not', 'but', 'can', 'will', 'just', 'from',
    'they', 'been', 'would', 'could', 'should', 'what', 'when', 'where',
    'which', 'there', 'their', 'about', 'into', 'them', 'then', 'than',
    'its', 'also', 'more', 'some', 'make', 'like', 'need', 'want',
    'get', 'use', 'let', 'going', 'now', 'know', 'see', 'way', 'all',
    'how', 'out', 'our', 'one', 'two', 'new', 'first', 'thing', 'things',
    'right', 'think', 'okay', 'sure', 'well', 'look', 'here', 'file',
    'code', 'run', 'add', 'check', 'please', 'thanks', 'yes', 'it\'s',
    'don\'t', 'i\'m', 'we\'re', 'that\'s', 'let\'s', 'we\'ve', 'i\'ve',
  ]);

  for (const msg of allUserMessages) {
    const words = msg.toLowerCase().split(/\s+/).filter(w =>
      w.length > 3 && !stopWords.has(w)
    );
    const seen = new Set();
    for (const word of words) {
      if (!seen.has(word)) {
        wordFreq[word] = (wordFreq[word] || 0) + 1;
        seen.add(word);
      }
    }
  }

  const topTerms = Object.entries(wordFreq)
    .filter(([, count]) => count >= 3)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
    .map(([word, count]) => `"${word}" mentioned in ${count} messages`);

  if (topTerms.length === 0) return null;

  return {
    title: 'Frequent Topics (candidates for CLAUDE.md)',
    description: 'These terms appear repeatedly in your messages — consider encoding this context:',
    items: topTerms,
  };
}

function detectToolPreferences(stats) {
  const items = [];

  const topTools = Object.entries(stats.toolUsage)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  for (const [tool, count] of topTools) {
    items.push(`${tool}: used ${count} times`);
  }

  if (items.length === 0) return null;

  return {
    title: 'Tool Usage Patterns',
    description: null,
    items,
  };
}
